id: PEA241C92
initial_creation_type: input
source_metadata:
  Title: Abhidharmāmṛta
  Editor: Shantibhiksu Shastri
  Publisher: Visvabharati
  Place of Publication: Shantiniketan, Calcutta, India
  Year: '1953'
  Prathamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Dvitīyo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Tṛtīyo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Caturthā binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Paṃcamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ṣaṣṭho binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Saptamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Aṣṭamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Navamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Daśamo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Dvādaśo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Trayodaśo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Caturdaśo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Paṃcadaśo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ṣoḍaśo binduḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:17:27.266331'
last_modified_at: '2022-03-08T16:17:27.266340'
